Implemented parsing of template arguments
mangrove-lang/mangrove-vscode pull request #2
Opened 2023-03-02 20:51 UTC by Nykseli

2023-03-03 15:04 UTC, dragonmux requested changes
Looking good, there are a couple of queries to address and a couple of formatting items, but otherwise this seems nearly merge ready :)

Thank you for the contribution!

2023-03-03 15:04 UTC, dragonmux commented on src/server/parser/parser.ts
> +			return Err('IncorrectToken')
In this context, it might make more sense to emit UnreachableState here; but this works too

2023-03-03 15:04 UTC, dragonmux commented on src/server/parser/parser.ts
> +				return value as Result<undefined, ParsingErrors>
isResultError() should enforce this is an `Err<ParsingErrors>` object, removing the need to `as` it

2023-03-04 13:22 UTC, Nykseli commented on src/server/ast/values.ts
> +
There's no need for constructor. The `ASTNodeData` base class has the needed constructor and there's no need to call `super()` in JavaScript!

2023-03-04 14:00 UTC, dragonmux requested changes
Looks much better, thank you :) we spotted just one further mistake (did we miss that the first time?) with brace layout and with that fixed, we'll merge

2023-03-04 14:00 UTC, dragonmux commented on src/server/parser/parser.ts
> +		while (!endTmplToken(token)) {
{ on its own line

2023-03-04 14:22 UTC, dragonmux approved these changes
LGTM, merging

2023-03-04 14:24 UTC, merged